### ISSUE TITLE
deploy as docker container

### ISSUE THREAD

**Issue by vgheo** [sdaps/sdaps#112]
In order to reach a larger user base - including windows users - sdaps could provide a Dockerfile that allows creation of a docker image to be run in containers on both Linux and Windows.

dockerfile (proposed)
- install dependencies
- build from sources ( git clone - form last stable tag, setup.py install )
- setup default project dir
  - shared with host

sdaps container features
- allows execution of sdaps command
- shared directories with the host - for project data files transfer
- functions as described on the [Download/Windows](https://sdaps.org/Download/) page.

refs
- [Docker for windows](https://docs.docker.com/docker-for-windows/)

**Comment by benzea** [comment]
Sounds reasonable, I am happy to host images and such, but not sure I will get around to actually creating a docker file (one reason is that I simply cannot test it on Windows).

**Comment by bls8m** [comment]
a dockerfile would be awesome!

**Comment by benzea** [comment]
Someone on IRC (sakalauskas) just pointed me to this https://github.com/tfitz/docker-sdaps

**Comment by benzea** [comment]
I created a "docker" repo, and am happy to add more people to it.

I also tried to create an organisation on https://hub.docker.com, however, it appears someone registered a user "sdaps" and actually put a docker image there for us. Anyone knows who that might be or how we could contact them? I believe we want to get that account deleted so that we can create a proper "sdaps" organisation.

**Comment by vgheo** [comment]
https://github.com/vgheo/sdaps/blob/master/docker/Dockerfile

This is derived from the debian (ppa) build on master.

Currently fails with 
E: Unable to locate package python3-opencv

What ubuntu version should it build on ?

**Comment by vgheo** [comment]
Successfully built docker image from 1.2.1 ( ubuntu 14.4)
https://github.com/vgheo/sdaps/blob/stable/docker/Dockerfile

to do:
- setup CMD
- windows/unix wrapper scripts
- allow GUI on windows ( Xming )
- use multi-stage image ( stage 1 build, stage 2 runtime) - minimize image size
- review dependencies included in docker image ( build / runtime / suggested )

**Comment by vgheo** [comment]
Updated https://github.com/vgheo/sdaps/blob/stable/docker/Dockerfile
- entry point 
- runtime as second stage ( runtime image has 1.86GB)

Issues:
- sdaps prj gui fails to start -  "ImportError: cannot import name Gtk"
-- probably due to wrong/missing dependencies

Please review

**Comment by benzea** [comment]
Oh, SDAPS 1.2.1 is *ancient* unfortunately. I think we really want 1.9.3 here which will also require a much newer Ubuntu version to work …

**Comment by vgheo** [comment]
Hi,
At the moment when I submitted this issue, only 14.04 was supported by the ppa debian package - hence I had to install from sources.
I now see that the ppa supports bionic (18.04) in the latest package release.

There are 2 alternatives for using Docker
A) build deb package, deploy to ppa, build image using deb
B) build from source in a docker image, deploy in second stage docker image

If the debian package is to be maintained, alternative A makes more sense, as it has a simpler docker file (and avoids duplication of the build/runtime dependencies specification on the deb control file vs Dockerfile).

I have provided a poc for B ( as a replacement of the deb package ).
It is no problem to setup the dockerfile to build on 18.04 - just match the dependencies.

Can you please clarify which option will be chosen ?

**Comment by benzea** [comment]
I don't have a strong opinion on that :)

I'll try to keep the PPA updated. There were various reasons for the stable PPA packags to be really outdated and it hopefully won't be that bad again in the future.
